### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL '/login/cert': No schema supplied.

### ISSUE THREAD

**Issue by mawxcarroll** [arthepsy/pan-globalprotect-okta#12]
I'm just trying out your code for the first time and first of all -- thank you! It's awesome that people are working on this. My school just switched to Pan-GP with okta and I haven't been able to access the VPN from my Ubuntu system.

I'm hoping that I'm just doing something simple wrong. I used a QR reader to get my totp secret and I *think* I've set up the config file correctly:
`debug = 0
vpn_url = https://vpn.ursinus.edu
okta_url = https://ursinus.okta.com
username = ########
password = ########
totp.okta =  ###################
#totp.google = ABCDEFGHIJKLMNOP
#gateway = Manual ny1-gw.example.com
#openconnect_cmd = sudo openconnect
openconnect_args =                    # optional arguments to openconnect
execute = 0                           # execute openconnect command
bug.nl = 0                            # newline work-around for openconnect
bug.username = 0                      # username work-around for openconnect`

I get the following error when I run:

`~/git-repos/arthespy-okta$ ./gp-okta.py gp-okta.conf 
[INFO] prelogin request
[INFO] okta saml request
[INFO] okta auth request
[INFO] sessionToken: 201116eJg70sxUsqIiW_ZuqZlAKqJRPTccwWsiLnAFytuvuODEfRbvL
[INFO] okta redirect request
[INFO] okta redirect form request
Traceback (most recent call last):
  File "./gp-okta.py", line 379, in <module>
    main()
  File "./gp-okta.py", line 342, in main
    saml_username, prelogin_cookie = okta_redirect(conf, s, token, redirect_url)
  File "./gp-okta.py", line 286, in okta_redirect
    r = s.post(url, data=data)
  File "/home/tcarroll/.local/lib/python2.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/tcarroll/.local/lib/python2.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/tcarroll/.local/lib/python2.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/tcarroll/.local/lib/python2.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/home/tcarroll/.local/lib/python2.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/login/cert': No schema supplied. Perhaps you meant http:///login/cert?
`
Any advice would be helpful!

Thanks!

Cheers,
tom

**Comment by mawxcarroll** [comment]
Okay, I think I've made some progress in understanding exactly where things go wrong.

When the script gets to the "okta redirect request," it finds the url https://xxxxx.okta.com/login/sessionCookieRedirect, which I gather is correct. After posting to that url, the script seems to be expecting something that will contain the saml-username and the prelogin-cookie. However, by pasting that url into a browser, I can see that it's just the page that either sends the push to the okta app on my phone or requests the sms code. (Apparently, I can also request my tech support to set up Yubikey for me -- I have no idea whether or not that might be easier.)

If I click on the send push button, it takes me to a "login successful" page. The source for that page clearly has the saml-username and the prelogin-cookie.

I'm a bit stuck here. It seems like I need to make the script provide some input to activate the button and send the push to my phone.

**Comment by arthepsy** [comment]
From output You provided:
```
[INFO] okta redirect request
[INFO] okta redirect form request
```
I can see that it fails here:
```
        url, data = parse_form(xhtml)
        log('okta redirect form request')
        r = s.post(url, data=data)
```
Meaning that it parsed HTML response from `/login/sessionCookieRedirect` and found `form` action as `/login/cert`, not the full URL. I can probably fix that by prefixing URL with current path, but I'm not sure I've seen `/login/cert` at all. Usually, the form contains url to `/SAML20/SP/ACS` or something.

I am not sure how to continue this, as I haven't seen such behavior, without some test account or full debug logs.

**Comment by mawxcarroll** [comment]
Yes, this is what I'm seeing! There's an "intermediate" web page where it asks me to click a button to send the push to my phone. If I do that interactively, it makes it to a page like you describe, with something like  `/SAML20/SP/ACS`.

I'm at work but as soon as I get home I will attach the full debug logs. Let me know what else I can do to help.

Thanks!

**Comment by dlenski** [comment]
> Meaning that it parsed HTML response from `/login/sessionCookieRedirect` and found form action as `/login/cert`, not the full URL. I can probably fix that by prefixing URL with current path, but I'm not sure I've seen `/login/cert` at all. Usually, the form contains url to `/SAML20/SP/ACS` or something.

@arthepsy, I think you already know this, but you should be using [`urllib.urljoin(url_of_current_page, url_fragment)`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin) to combine the current and new URLs in a way that exactly matches what browsers do.

**Comment by arthepsy** [comment]
@dlenski yes, I'm aware, but I don't think that this will help, as I'm not sure what `/login/cert` expects and responds...

**Comment by dlenski** [comment]
Is it possible that `/login/cert` is simply a step where a client certificate is expected to be included in the request… and assuming the client cert is good it'll just redirect to a subsequent step?

(I've seen a couple non-GP VPNs that use a similar step, where only _one_ request in the authentication process actually needs the client cert…)

**Comment by arthepsy** [comment]
I'm wondering why it got further than `/login/cert` in Your debug log. Did You made some changes locally?

**Comment by mawxcarroll** [comment]
Ah! Sorry, yes, I had hard-coded the correct saml-username and was trying to get it to move a bit further in the process. Here's the command line output from the unmodified code with the full debug output here: 
[debug.txt](https://github.com/arthepsy/pan-globalprotect-okta/files/2789827/debug.txt)


> $ ./gp-okta.py gp-okta.conf > debug.txt
Traceback (most recent call last):
  File "./gp-okta.py", line 424, in <module>
    main()
  File "./gp-okta.py", line 387, in main
    saml_username, prelogin_cookie = okta_redirect(conf, s, token, redirect_url)
  File "./gp-okta.py", line 331, in okta_redirect
    r = s.post(url, data=data)
  File "/home/tcarroll/.local/lib/python2.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/tcarroll/.local/lib/python2.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/tcarroll/.local/lib/python2.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/tcarroll/.local/lib/python2.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/home/tcarroll/.local/lib/python2.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/login/cert': No schema supplied. Perhaps you meant http:///login/cert?

**Comment by arthepsy** [comment]
@mawxcarroll I reviewed Your debug.txt, compared with mine. Commited a patch, that does redirection dance, until it gets `prelogin-cookie`. Please, test it now and give feedback.

**Comment by mawxcarroll** [comment]
@arthepsy I tried the new version, and it definitely yields a different error:
[debug.txt](https://github.com/arthepsy/pan-globalprotect-okta/files/2792325/debug.txt)

> $ ./gp-okta.py gp-okta.conf 
[INFO] prelogin request
[INFO] okta saml request
[INFO] okta auth request
[INFO] sessionToken: 20111uqU4ajN3S6LHOyOSLMFbhF0u7avbepS7eyDjA5hDSTgI-HreNv
[INFO] okta redirect request
[INFO] okta redirect request
[INFO] okta redirect request
[INFO] okta redirect request
[INFO] okta redirect request
[INFO] okta redirect request
[INFO] okta redirect request
[INFO] okta redirect request
[INFO] okta redirect request
[INFO] okta redirect request
[INFO] okta redirect request
err: redirect rabbit hole is too deep...

**Comment by alessiostalla** [comment]
I'm getting the same error as @mawxcarroll . This is the last request:

**Comment by alessiostalla** [comment]
This appears to be my org's login page, so I think the redirect is a red herring, something's not working in the previous requests.
